# Generated by Django 3.2 on 2022-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isSubCategory',
            field=models.BooleanField(default=False),
        ),
    ]
