# Generated by Django 3.2 on 2022-04-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20220416_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tagline',
            new_name='description',
        ),
    ]
